#!/usr/bin/env sh
# cliv v0.1.0 - Execute commands using a specific directory of files and variables
# Copyright (C) 2021 Peter Willis
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLIV_HTTP_PATH="${CLIV_HTTP_PATH:-https://raw.githubusercontent.com/peterwwillis/cliv/main}"
HOME="${HOME:-$(getent passwd $(id -u) | cut -d : -f 6)}"
export CLIV_DIR="${CLIV_DIR:-$HOME/.cliv}"

### General cliv functions
_usage () {
    printf "%s\n" "
Usage: $0 [OPTS]
       $0 [OPTS] [ALIAS [CMD [ARGS ..]] ]
Opts:
	-h			This screen
	-i			Clear environment variables. Must be first argument
	-l [ALIAS]		List versions
	-n ALIAS		Create a new ALIAS
	-I EXT[=V] [ALIAS] 	Install version V of extension EXT into ALIAS
	-W EXT [-- CMD ..]	Installs extension EXT and runs CMD
	-f			Force mode
"
  exit 1
}
_err () { printf "%s\n" "$0: Error: $*" ; exit 1 ; }
_cliv_list () {
    for d in "$@" ; do
        [ -d "$CLIV_DIR/$(basename "$d")" ] && basename "$d"
    done
}
_cliv_new () {
    export CLIV_E_ALIAS="$1" ; shift
    if [ -d "$CLIV_DIR/$CLIV_E_ALIAS" ] && [ ! "$CLIV_FORCE" = "1" ] ; then
        _err "Version '$CLIV_DIR/$CLIV_E_ALIAS' already exists"
    fi
    mkdir -p "$CLIV_DIR/$CLIV_E_ALIAS/bin"
    echo "PATH=$CLIV_DIR/$CLIV_E_ALIAS/bin:\$PATH" > "$CLIV_DIR/$CLIV_E_ALIAS/.env"
}
_cliv_ext_run () {  "$CLIV_DIR/.ext/$CLIV_E_NAME" "$@"; }
_cliv_ext_install () {
    ext="${1%%=*}" ver="${1#*=}" alias="${2:-}"
    if [ $# -lt 2 ] ; then shift 1; alias="$ext"; else shift 2; fi
    if [ ! "$ver" = "$ext" ] ; then
        export CLIV_E_VERSION="$ver"
    fi
    export CLIV_E_NAME="$ext" CLIV_E_ALIAS="$alias" CLIV_E_INSTDIR="$CLIV_DIR/$alias"

    if [ ! -e "$CLIV_DIR/.ext/$CLIV_E_NAME" ] || [ "$CLIV_FORCE" = "1" ] ; then
        echo_err "Installing extention $CLIV_E_NAME"
        if   command -v curl >/dev/null ; then  curl -fsSL -o "$CLIV_DIR/.ext/$CLIV_E_NAME" "$CLIV_HTTP_PATH/.ext/$CLIV_E_NAME"
        elif command -v wget >/dev/null ; then  wget -O "$CLIV_DIR/.ext/$CLIV_E_NAME" "$CLIV_HTTP_PATH/.ext/$CLIV_E_NAME"
        else _err "Please install 'curl' or 'wget'." ; fi
        chmod 755 "$CLIV_DIR/.ext/$CLIV_E_NAME"
        _ext_install_wrapper
    fi

    [ -z "${CLIV_E_VERSION:-}" ] && CLIV_E_VERSION="latest"
    [ "$CLIV_E_VERSION" = "latest" ] && CLIV_E_VERSION="$(_cliv_ext_run latest)"
    [ -d "$CLIV_DIR/$CLIV_E_ALIAS" ] || _cliv_new "$CLIV_E_ALIAS"
    export CLIV_E_VERSION="$CLIV_E_VERSION"
    echo_err "Loading $CLIV_E_NAME version '$CLIV_E_VERSION'"
    _ext_clean; _ext_download; _ext_unpack; _ext_install_local; _ext_test; _ext_clean
    echo_err ""
}
_cliv_exec () {
  export CLIV_E_ALIAS="$1" ; shift
  [ -d "$CLIV_DIR/$CLIV_E_ALIAS" ] || _err "No version '$CLIV_DIR/$CLIV_E_ALIAS' found"

  if [ -r "$CLIV_DIR/$CLIV_E_ALIAS/.env" ] ; then
      set -a
      . "$CLIV_DIR/$CLIV_E_ALIAS/.env"
  else echo_err "Warning: no '$CLIV_DIR/$CLIV_E_ALIAS/.env' found" ; fi
  echo_err "Executing $(which "$1")"
  exec env "$@"
}
_cliv_wrapper () {
    CLIV_E_NAME="$CLIV_WRAPPER"
    CLIV_E_ALIAS="${CLIV_E_ALIAS:-$CLIV_E_NAME}" # Default alias to extension name
    if [ -z "${CLIV_E_VERSION:-}" ] ; then
        cwd="$(pwd)"
        while [ ! "$(dirname "$cwd")" = "/" ] ; do
            echo_err "Looking for '$cwd/.$CLIV_E_NAME-version"
            if [ -r "$cwd/.$CLIV_E_NAME-version" ] ; then
                CLIV_E_VERSION="$(cat "$cwd/.$CLIV_E_NAME-version")"
                echo_err "Found '$cwd/.$CLIV_E_NAME-version' = '$CLIV_E_VERSION'"
                break
            else
                cwd="$(dirname "$cwd")"
            fi
        done
    fi
    extfull="$CLIV_E_NAME" aliasfull="$CLIV_E_ALIAS"
    if [ -n "${CLIV_E_VERSION:-}" ] ; then
        extfull="$extfull=$CLIV_E_VERSION"
        aliasfull="$aliasfull=$CLIV_E_VERSION"
    fi
    cliv -l "$aliasfull" >/dev/null || cliv -I "$extfull" "$aliasfull"
    cliv "$aliasfull" "$@"
}

### Extension functions
echo_err () { printf "%s\n" "$(basename "$0"): $*" 1>&2 ; }
echo_info () { printf "%s\n" "$(basename "$0"): $*" ; }
_ext_test () {          echo_err "$CLIV_E_NAME: Testing"; _cliv_ext_run "test"; }
_ext_clean_install () { echo_err "$CLIV_E_NAME: Removing '$CLIV_E_INSTDIR'"; _cliv_ext_run "clean-install"; }
_ext_clean () {         echo_err "$CLIV_E_NAME: Removing temporary download files"; _cliv_ext_run "clean"; }
_ext_install_global () { echo_err "$CLIV_E_NAME: Installing globally" ; _cliv_ext_run "install-global"; }
_ext_install_local () { echo_err "$CLIV_E_NAME: Installing symlink"; _cliv_ext_run "install-local"; }
_ext_install_wrapper () {       echo_err "$CLIV_E_NAME: Installing wrapper"; _cliv_ext_run "install-wrapper"; }
_ext_unpack () {        echo_err "$CLIV_E_NAME: Unpacking to '$CLIV_E_INSTDIR'"; _cliv_ext_run "unpack"; }
_ext_download () {      echo_err "$CLIV_E_NAME: Downloading artifact"; _cliv_ext_run "download" "$CLIV_E_VERSION"; }
_ext_usage () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$CLIV_DIR/.ext/$CLIV_E_NAME" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

### Main program
if [ $# -lt 1 ] ; then
    _usage
fi

[ "$1" = "-i" ] && shift 1 && exec env -i "$0" "$@"

CLIV_NEW=0 CLIV_LIST=0 CLIV_FORCE=0
while getopts "nlI:W:f" args ; do
    case "$args" in
        n)  CLIV_NEW=1 ;;
        l)  CLIV_LIST=1 ;;
        I)  CLIV_LOAD="$OPTARG" ;;
        W)  CLIV_WRAPPER="$OPTARG" ;;
        f)  export CLIV_FORCE=1 ;;
    esac
done
shift $(($OPTIND-1))

for d in "$CLIV_DIR" "$CLIV_DIR/.bin" "$CLIV_DIR/.ext" ; do
    [ -d "$d" ] || mkdir -p "$d"
done

if [ -n "${CLIV_WRAPPER:-}" ] ; then
    _cliv_wrapper "$@"
    exit 0
elif [ $CLIV_NEW -eq 1 ] ; then
    _cliv_new "$@"
    exit 0
elif [ $CLIV_LIST -eq 1 ] ; then
    if [ $# -gt 0 ] ; then  _cliv_list "$@"
    else _cliv_list "$CLIV_DIR"/*
    fi
    exit 0
elif [ -n "${CLIV_LOAD:-}" ] ; then
    _cliv_ext_install "$CLIV_LOAD" "$@"
    exit 0
fi

if [ $# -gt 0 ] ; then
    _cliv_exec "$@"
fi
