#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLENV_E_NAME="${CLENV_E_NAME:-aws}"
CLENV_E_REV="0.3.0"
CLENV_E_OS="${CLENV_E_OS:-linux}"
CLENV_E_ARCH="${CLENV_E_ARCH:-x86_64}"
CLENV_E_BIN_NAME="${CLENV_E_BIN_NAME:-aws}"
CLENV_E_DLFILE="${CLENV_E_DLFILE:-$CLENV_E_NAME.zip}"
CLENV_E_INSTDIR="${CLENV_E_INSTDIR:-$(pwd)}"

CLENV_E_GHREPOAPI="https://api.github.com/repos/aws/aws-cli"
CLENV_E_HCURL="https://awscli.amazonaws.com"
CLENV_E_BASEURL="$CLENV_E_HCURL/awscli-exe-%s-%s-%s.zip"

_ext_versions () {
    # technically '/releases' is better but tags are the same here and this is 1/100th the bandwidth
    next_url="$CLENV_E_GHREPOAPI/tags"
    echo "$0: Warning: retrieving list of aws-cli versions; this will take some time..." 1>&2
    while [ -n "$next_url" ] ; do
        output="$(curl -ifsSL "$next_url")"
        printf "%s\n" "$output" | awk -F '"' '/"name":/{print $4}' | sed -e 's/^v//'
        next_url="$(printf "%s\n" "$output" | grep '^link:' \
            | sed -e 's/link: //; s/, /\n/g; s/[<>]//g; s/; rel/ rel/g; s/\(https:\/\/[^ ]\+\) rel="\([a-z]\+\)"/\2 \1/g' \
            | awk '/next / { print $2}')"
    done
}
_ext_url () {  printf "$CLENV_E_BASEURL\n" "$CLENV_E_OS" "$CLENV_E_ARCH" "$CLENV_E_VERSION" ; }
_ext_unpack () {
    mkdir -p "$CLENV_E_INSTDIR/usr/share"
    unzip -q -o -d "$CLENV_E_INSTDIR/usr/share" "$CLENV_E_INSTDIR/download/$CLENV_E_DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLENV_E_INSTDIR/usr/share/aws/dist/aws" "bin/$CLENV_E_BIN_NAME"
}
_ext_variables () { set | grep '^CLENV_E_' ; }
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 0
}

if [ $# -lt 1 ] ; then  _ext_help
else cmd="$1"; shift; func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLENV_DIR:-}" -a -n "${CLENV_E_ENVIRON:-}" ] ; then 
        [ -d "$CLENV_DIR/$CLENV_E_ENVIRON" ] && cd "$CLENV_DIR/$CLENV_E_ENVIRON"
    fi
    case "$cmd" in *) $func "$@" ;; esac
fi
