#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLENV_E_NAME="${CLENV_E_NAME:-aws-cli}"
CLENV_E_REV="0.1.0"

CLENV_E_OS="${CLENV_E_OS:-linux}"
CLENV_E_ARCH="${CLENV_E_ARCH:-x86_64}"

CLENV_E_BIN_NAME="${CLENV_E_BIN_NAME:-aws}"
CLENV_E_DLFILE="${CLENV_E_DLFILE:-$CLENV_E_NAME.zip}"

_GHREPOAPI="https://api.github.com/repos/aws/$CLENV_E_NAME"
_HCURL="https://awscli.amazonaws.com"
BASEURL="$_HCURL/awscli-exe-%s-%s-%s.zip"

CLENV_E_INSTDIR="${CLENV_E_INSTDIR:-$(pwd)}"

_ext_latest () {
    _ext_versions | head -1
}
_ext_versions () {
    # technically '/releases' is better but tags are the same here and this is 1/100th the bandwidth
    next_url="$_GHREPOAPI/tags"
    echo "$0: Warning: retrieving list of aws-cli versions; this will take some time..." 1>&2
    # yes, this is very ugly. please feel free to give it a facelift...
    while [ -n "$next_url" ] ; do
        output="$(curl -ifsSL "$next_url")"
        printf "%s\n" "$output" | awk -F '"' '/"name":/{print $4}' | sed -e 's/^v//'
        next="$(printf "%s\n" "$output" | grep '^link:' \
            | sed -e 's/link: //; s/, /\n/g; s/[<>]//g; s/; rel/ rel/g; s/\(https:\/\/[^ ]\+\) rel="\([a-z]\+\)"/\2 \1/g' \
            | awk '/next / { print $2}')"
        if [ -n "${next:-}" ] ; then
                next_url="$next"
        else    next_url=""
        fi
    done
}
_ext_url () {
    if [ $# -lt 1 ] || [ $# -gt 0 -a "$1" = "latest" ] ; then
            CLENV_E_VERSION="$(_ext_latest)"
    else    CLENV_E_VERSION="$1"
    fi
    printf "$BASEURL\n" "$CLENV_E_OS" "$CLENV_E_ARCH" "$CLENV_E_VERSION"
}
_ext_download () {
    mkdir -p "$CLENV_E_INSTDIR/download"
    curl -fSL "$(_ext_url "$@")" -o "$CLENV_E_INSTDIR/download/$CLENV_E_DLFILE"
}
_ext_unpack () {
    mkdir -p "$CLENV_E_INSTDIR/usr/share"
    unzip -q -o -d "$CLENV_E_INSTDIR/usr/share" "$CLENV_E_INSTDIR/download/$CLENV_E_DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLENV_E_INSTDIR/usr/share/aws/dist/aws" "bin/$CLENV_E_BIN_NAME"
}
_ext_install_global () {
    if [ -e /usr/local/aws-cli/v2/current ] ; then
        sudo "$CLIV_E_INSTDIR/usr/share/aws/install" --update
    else
        sudo "$CLIV_E_INSTDIR/usr/share/aws/install"
    fi
}
_ext_install_wrapper () {
    [ -d "$CLENV_DIR/.bin" ] || mkdir -p "$CLENV_DIR/.bin"
    printf "#!/usr/bin/env sh\nexec clenv -W $CLENV_E_NAME $CLENV_E_ENVIRON $CLENV_E_BIN_NAME \"\$@\"\n" > "$CLENV_DIR/.bin/$CLENV_E_BIN_NAME"
    chmod 755 "$CLENV_DIR/.bin/$CLENV_E_BIN_NAME"
}
_ext_clean () {
    rm -rf "$CLENV_E_INSTDIR/download/"
}
_ext_clean_install () {
    rm -rf "$CLENV_E_INSTDIR"
}
_ext_test () {
    "./bin/$CLENV_E_BIN_NAME" --version
}
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

if [ $# -lt 1 ] ; then
    _ext_help
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLENV_DIR:-}" -a -n "${CLENV_E_ENVIRON:-}" ] ; then
        [ -d "$CLENV_DIR/$CLENV_E_ENVIRON" ] && cd "$CLENV_DIR/$CLENV_E_ENVIRON"
    fi
    case "$cmd" in 
        *)                  $func "$@" ;;
    esac
fi
