#!/bin/sh
# CLIV EXTENSION: aws-cli-v2
set -eu
EXT_VER="1.0"
VERSION="2.1.37"
INSTDIR="${INSTDIR:-$(pwd)/usr}"

_usage () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}
_url () {
    if [ $# -gt 0 ] && [ "$1" = "latest" ] ; then
         printf "%s\n" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    else printf "%s\n" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-$1.zip"
    fi
}
_ext_download () {  echo "$0: Downloading awscliv2.zip"
    [ $# -gt 0 ] && [ -n "$1" ] && VERSION="$1"
    url="$(_url "$VERSION")"
    [ -e awscliv2.zip ] || curl -L "$url" -o awscliv2.zip
}
_ext_unpack () {  echo "$0: Unpacking awscliv2 to '$INSTDIR'"
    unzip -q -o -d "$INSTDIR" awscliv2.zip
}
_ext_install_local () {  echo "$0: Installing symlink to '$INSTDIR/aws/dist/aws' in bin/aws"
    ln -sf "$INSTDIR"/aws/dist/aws bin/aws
}
_ext_install_global () {  echo "$0: Installing globally with '$INSTDIR/aws/install'"
    if [ -e /usr/local/aws-cli/v2/current ] ; then
        sudo "$INSTDIR"/aws/install --update
    else
        sudo "$INSTDIR"/aws/install
    fi
}
_ext_clean () {  echo "$0: Removing awscliv2.zip"
    rm -f awscliv2.zip
}
_ext_clean_install () {  echo "$0: Removing '$INSTDIR'"
    rm -rf "$INSTDIR"
}
_ext_test () {  echo "$0: Testing '$INSTDIR/aws/dist/aws'"
    "$INSTDIR/aws/dist/aws" --version
}
_ext_load () {
    extver="latest"
    [ $# -gt 0 ] && [ -n "$1" ] && extver="$1"
    echo "$0: Loading extension version '$extver'"
    $0 clean
    $0 download "$extver"
    $0 unpack
    $0 install-local
    $0 test
    $0 clean
}

if [ $# -lt 1 ] ; then
    _usage
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    case "$cmd" in 
        -h|--help)          _usage ;;
        clean-all)              $0 clean; $0 clean-install ;;
        install)            $0 install-local ;;
        *)
                            $func "$@" ;;
    esac
fi
