#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLENV_E_NAME="${CLENV_E_NAME:-packer}"
CLENV_E_REV="0.2.0"
CLENV_E_BIN_NAME="${CLENV_E_BIN_NAME:-$CLENV_E_NAME}"
CLENV_E_DLFILE="${CLENV_E_DLFILE:-$CLENV_E_NAME.zip}"
CLENV_E_INSTDIR="${CLENV_E_INSTDIR:-$(pwd)}"

CLENV_E_OS="${CLENV_E_OS:-linux}"
CLENV_E_ARCH="${CLENV_E_ARCH:-amd64}"

CLENV_E_HCURL="https://releases.hashicorp.com/$CLENV_E_NAME"
CLENV_E_BASEURL="$_HCURL/%s/$CLENV_E_NAME""_%s_%s_%s.zip"

### Core functions
_ext_versions () {  clenv -X versions_hc "$CLENV_E_HCURL" ;  }
_ext_url () {  printf "$BASEURL\n" "$CLENV_E_VERSION" "$CLENV_E_VERSION" "$CLENV_E_OS" "$CLENV_E_ARCH";  }
_ext_unpack () {
    mkdir -p "$CLENV_E_INSTDIR/usr/bin"
    unzip -q -o -d "$CLENV_E_INSTDIR/usr/bin" "$CLENV_E_INSTDIR/download/$CLENV_E_DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLENV_E_INSTDIR/usr/bin/$CLENV_E_BIN_NAME" "bin/$CLENV_E_BIN_NAME"
}

### The rest of this doesn't need to be modified
_ext_variables () { set | grep '^CLENV_E_' ; }
_ext_help () {
    printf "Usage: $0 CMD\n\nCommands:\n%s\n" "$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)"
    exit 0
}
if [ $# -lt 1 ] ; then  _ext_help
else cmd="$1"; shift; func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLENV_DIR:-}" -a -n "${CLENV_E_ENVIRON:-}" ] ; then 
        [ -d "$CLENV_DIR/$CLENV_E_ENVIRON" ] && cd "$CLENV_DIR/$CLENV_E_ENVIRON"
    fi
    case "$cmd" in *) $func "$@" ;; esac
fi
