#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLENV_E_NAME="${CLENV_E_NAME:-saml2aws}"
CLENV_E_REV="0.1.0"

SAML2AWS_OS="${SAML2AWS_OS:-linux}"
SAML2AWS_ARCH="${SAML2AWS_ARCH:-amd64}"

BIN_NAME="$CLENV_E_NAME"
DLFILE="$CLENV_E_NAME.tar.gz"
_GHREPOAPI="https://api.github.com/repos/Versent/$CLENV_E_NAME"
_GHURL="https://github.com/Versent/$CLENV_E_NAME/releases"
BASEURL="$_GHURL/download/v%s/$CLENV_E_NAME""_%s_%s_%s.tar.gz"

CLENV_E_INSTDIR="${CLENV_E_INSTDIR:-$(pwd)/usr/bin}"

_ext_latest () {
    _ext_versions | head -1
}
_ext_versions () {
    # technically '/releases' is better but tags are the same here and this is 1/100th the bandwidth
    curl -sL "$_GHREPOAPI/tags" | awk -F '"' '/"name":/{print $4}' | sed -e 's/^v//'
}
_ext_url () {
    if [ $# -lt 1 ] || [ $# -gt 0 -a "$1" = "latest" ] ; then
            CLENV_E_VERSION="$(_ext_latest)"
    else    CLENV_E_VERSION="$1"
    fi
    printf "$BASEURL\n" "$CLENV_E_VERSION" "$CLENV_E_VERSION" "$SAML2AWS_OS" "$SAML2AWS_ARCH"
}
_ext_download () {
    curl -L "$(_ext_url "$@")" -o $DLFILE
}
_ext_unpack () {
    mkdir -p "$CLENV_E_INSTDIR"
    tar -C "$CLENV_E_INSTDIR" -xzf "$DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLENV_E_INSTDIR"/$BIN_NAME bin/$BIN_NAME
}
_ext_install_global () {
    sudo /bin/sh -c "mkdir -p /usr/local/bin; mv $BIN_NAME /usr/local/bin/$BIN_NAME"
}
_ext_install_wrapper () {
    [ -d "$CLENV_DIR/.bin" ] || mkdir -p "$CLENV_DIR/.bin"
    printf "#!/usr/bin/env sh\nexec clenv -W $CLENV_E_NAME $BIN_NAME \"\$@\"\n" > "$CLENV_DIR/.bin/$CLENV_E_NAME"
    chmod 755 "$CLENV_DIR/.bin/$CLENV_E_NAME"
}
_ext_clean () {
    rm -f "$DLFILE"
}
_ext_clean_install () {
    rm -rf "$CLENV_E_INSTDIR"
}
_ext_test () {
    "./bin/$BIN_NAME" --version
}
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

if [ $# -lt 1 ] ; then
    _ext_help
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLENV_DIR:-}" -a -n "${CLENV_E_ALIAS:-}" ] ; then
        [ -d "$CLENV_DIR/$CLENV_E_ALIAS" ] && cd "$CLENV_DIR/$CLENV_E_ALIAS"
    fi
    case "$cmd" in 
        *)                  $func "$@" ;;
    esac
fi
