#!/bin/sh
# CLIV EXTENSION: terraform
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

EXT_VER="1.0"
INSTDIR="${INSTDIR:-$(pwd)/usr/bin}"

PROGRAM="terraform"
VERSION="0.15.0"
_HCURL="https://releases.hashicorp.com/$PROGRAM"
BASEURL="$_HCURL/%s/""$PROGRAM""_%s_linux_amd64.zip"
DLFILE="terraform.zip"

_usage () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}
_url () {
    if [ $# -gt 0 ] && [ "$1" = "latest" ] ; then
        VERSION="$( curl -sL "$_HCURL" | grep -e "<a href=\"/$PROGRAM/" | grep -v alpha | head -1 | cut -d \" -f 2 | cut -d / -f 3 )"
    fi
    printf "$BASEURL\n" "$VERSION" "$VERSION"
}
_ext_download () {
    [ $# -gt 0 ] && [ -n "$1" ] && VERSION="$1"
    url="$(_url "$VERSION")"
    fname="$(basename "$url")"
    echo "$0: Downloading $fname"
    curl -L "$url" -o $DLFILE
}
_ext_unpack () {  echo "$0: Unpacking $PROGRAM to '$INSTDIR'"
    mkdir -p "$INSTDIR"
    unzip -q -o -d "$INSTDIR" $DLFILE
}
_ext_install_local () {  echo "$0: Installing symlink: $INSTDIR/$PROGRAM -> bin/$PROGRAM"
    mkdir -p bin
    ln -sf "$INSTDIR"/$PROGRAM bin/$PROGRAM
}
_ext_install_global () {  echo "$0: Installing globally"
    sudo /bin/sh -c "mkdir -p /usr/local/bin; mv $PROGRAM /usr/local/bin/$PROGRAM"
}
_ext_clean () {  echo "$0: Removing $DLFILE"
    rm -f $DLFILE
}
_ext_clean_install () {  echo "$0: Removing '$INSTDIR'"
    rm -rf "$INSTDIR"
}
_ext_test () {  echo "$0: Testing $PROGRAM"
    ./bin/$PROGRAM --version
}
_ext_load () {
    extver="latest"
    [ $# -gt 0 ] && [ -n "$1" ] && extver="$1"
    echo "$0: Loading extension version '$extver'"
    $0 clean
    $0 download "$extver"
    $0 unpack
    $0 install-local
    $0 test
    $0 clean
}

if [ $# -lt 1 ] ; then
    _usage
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    case "$cmd" in 
        -h|--help)          _usage ;;
        clean-all)              $0 clean; $0 clean-install ;;
        install)            $0 install-local ;;
        *)
                            $func "$@" ;;
    esac
fi
