#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLENV_E_NAME="${CLENV_E_NAME:-terraform}"
CLENV_E_REV="0.1.2"

CLENV_E_OS="${CLENV_E_OS:-linux}"
CLENV_E_ARCH="${CLENV_E_ARCH:-amd64}"

BIN_NAME="$CLENV_E_NAME"
DLFILE="$CLENV_E_NAME.zip"
_HCURL="https://releases.hashicorp.com/$CLENV_E_NAME"
BASEURL="$_HCURL/%s/$CLENV_E_NAME""_%s_%s_%s.zip"

CLENV_E_INSTDIR="${CLENV_E_INSTDIR:-$(pwd)}"

_ext_latest () {
    _ext_versions | head -1
}
_ext_versions () {
    curl -sL "$_HCURL" | grep -e "<a href=\"/$CLENV_E_NAME/" | grep -v alpha | cut -d \" -f 2 | cut -d / -f 3 | sed -e 's/^v//'
}
_ext_url () {
    if [ $# -lt 1 ] || [ $# -gt 0 -a "$1" = "latest" ] ; then
            CLENV_E_VERSION="$(_ext_latest)"
    else    CLENV_E_VERSION="$1"
    fi
    printf "$BASEURL\n" "$CLENV_E_VERSION" "$CLENV_E_VERSION" "$CLENV_E_OS" "$CLENV_E_ARCH"
}
_ext_download () {
    mkdir -p "$CLENV_E_INSTDIR/download"
    curl -L "$(_ext_url "$@")" -o "$CLENV_E_INSTDIR/download/$DLFILE"
}
_ext_unpack () {
    mkdir -p "$CLENV_E_INSTDIR/usr/bin"
    unzip -q -o -d "$CLENV_E_INSTDIR/usr/bin" "$CLENV_E_INSTDIR/download/$DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLENV_E_INSTDIR/usr/bin/$BIN_NAME" "bin/$BIN_NAME"
}
_ext_install_global () {
    sudo /bin/sh -c "mkdir -p /usr/local/bin; mv $BIN_NAME /usr/local/bin/$BIN_NAME"
}
_ext_install_wrapper () {
    [ -d "$CLENV_DIR/.bin" ] || mkdir -p "$CLENV_DIR/.bin"
    printf "#!/usr/bin/env sh\nexec clenv -W $CLENV_E_NAME $BIN_NAME \"\$@\"\n" > "$CLENV_DIR/.bin/$CLENV_E_NAME"
    chmod 755 "$CLENV_DIR/.bin/$CLENV_E_NAME"
}
_ext_clean () {
    rm -rf "$CLENV_E_INSTDIR/download/"
}
_ext_clean_install () {
    rm -rf "$CLENV_E_INSTDIR"
}
_ext_test () {
    "./bin/$BIN_NAME" --version
}
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

if [ $# -lt 1 ] ; then
    _ext_help
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLENV_DIR:-}" -a -n "${CLENV_E_ENVIRON:-}" ] ; then
        [ -d "$CLENV_DIR/$CLENV_E_ENVIRON" ] && cd "$CLENV_DIR/$CLENV_E_ENVIRON"
    fi
    case "$cmd" in 
        *)                  $func "$@" ;;
    esac
fi
