#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CLIV_E_NAME="${CLIV_E_NAME:-terraformer}"
CLIV_E_REV="0.1.2"

TERRAFORMER_PLATFORM="${TERRAFORMER_PLATFORM:-aws}"
TERRAFORMER_OS="${TERRAFORMER_OS:-linux}"
TERRAFORMER_ARCH="${TERRAFORMER_ARCH:-amd64}"

BIN_NAME="$CLIV_E_NAME"
DLFILE="$CLIV_E_NAME"
_GHREPOAPI="https://api.github.com/repos/GoogleCloudPlatform/$BIN_NAME"
_GHURL="https://github.com/GoogleCloudPlatform/terraformer/releases"
BASEURL="$_GHURL/download/%s/terraformer-%s-%s-%s"

CLIV_E_INSTDIR="${CLIV_E_INSTDIR:-$(pwd)/usr/bin}"

_ext_latest () {
    _ext_versions | head -1
}
_ext_versions () {
    # technically '/releases' is better but tags are the same here and this is 1/100th the bandwidth
    curl -sL "$_GHREPOAPI/tags" | awk -F '"' '/"name":/{print $4}'
}
_ext_url () {
    if [ $# -lt 1 ] || [ $# -gt 0 -a "$1" = "latest" ] ; then
            CLIV_E_VERSION="$(_ext_latest)"
    else    CLIV_E_VERSION="$1"
    fi
    printf "$BASEURL\n" "$CLIV_E_VERSION" "$TERRAFORMER_PLATFORM" "$TERRAFORMER_OS" "$TERRAFORMER_ARCH"
}
_ext_download () {
    curl -L "$(_ext_url "$@")" -o $DLFILE
}
_ext_unpack () {
    mkdir -p "$CLIV_E_INSTDIR"
    chmod 755 "$DLFILE"
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CLIV_E_INSTDIR"/$BIN_NAME bin/$BIN_NAME
}
_ext_install_global () {
    sudo /bin/sh -c "mkdir -p /usr/local/bin; mv $BIN_NAME /usr/local/bin/$BIN_NAME"
}
_ext_install_wrapper () {
    [ -d "$CLIV_DIR/.bin" ] || mkdir -p "$CLIV_DIR/.bin"
    printf "#!/usr/bin/env sh\nexec cliv -W $CLIV_E_NAME $BIN_NAME \"\$@\"\n" > "$CLIV_DIR/.bin/$CLIV_E_NAME"
    chmod 755 "$CLIV_DIR/.bin/$CLIV_E_NAME"
}
_ext_clean () {
    rm -f "$DLFILE"
}
_ext_clean_install () {
    rm -rf "$CLIV_E_INSTDIR"
}
_ext_test () {
    "./bin/$BIN_NAME" --version
}
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

if [ $# -lt 1 ] ; then
    _ext_help
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLIV_DIR:-}" -a -n "${CLIV_E_ALIAS:-}" ] ; then
        [ -d "$CLIV_DIR/$CLIV_E_ALIAS" ] && cd "$CLIV_DIR/$CLIV_E_ALIAS"
    fi
    case "$cmd" in 
        *)                  $func "$@" ;;
    esac
fi
