#!/usr/bin/env sh
set -eu
[ "${DEBUG:-0}" = "1" ] && set -x

CV_EXT_NAME="${CV_EXT_NAME:-terraform}"
CV_EXT_VER="0.1.2"

BIN_NAME="terraform"
_HCURL="https://releases.hashicorp.com/$CV_EXT_NAME"
BASEURL="$_HCURL/%s/""$CV_EXT_NAME""_%s_linux_amd64.zip"
DLFILE="terraform.zip"
VERSION_FILE=".$CV_EXT_NAME-version"

CV_INSTDIR="${CV_INSTDIR:-$(pwd)/usr/bin}"

_ext_latest () {
    _ext_versions | head -1
}
_ext_versions () {
    curl -sL "$_HCURL" | grep -e "<a href=\"/$CV_EXT_NAME/" | grep -v alpha | cut -d \" -f 2 | cut -d / -f 3
}
_ext_url () {
    if [ $# -lt 1 ] || [ $# -gt 0 -a "$1" = "latest" ] ; then
            CV_VERSION="$(_ext_latest)"
    else    CV_VERSION="$1"
    fi
    printf "$BASEURL\n" "$CV_VERSION" "$CV_VERSION"
}
_ext_download () {
    curl -L "$(_ext_url "$@")" -o $DLFILE
}
_ext_unpack () {
    mkdir -p "$CV_INSTDIR"
    unzip -q -o -d "$CV_INSTDIR" $DLFILE
}
_ext_install_local () {
    mkdir -p bin
    ln -sf "$CV_INSTDIR"/$BIN_NAME bin/$BIN_NAME
}
_ext_install_global () {
    sudo /bin/sh -c "mkdir -p /usr/local/bin; mv $BIN_NAME /usr/local/bin/$BIN_NAME"
}
_ext_install_wrapper () {
    [ -d "$CLIV_DIR/.bin" ] || mkdir -p "$CLIV_DIR/.bin"
    printf "#!/usr/bin/env sh\nexec cliv -W $CV_EXT_NAME $BIN_NAME \"\$@\"\n" > "$CLIV_DIR/.bin/$CV_EXT_NAME"
    chmod 755 "$CLIV_DIR/.bin/$CV_EXT_NAME"
}
_ext_clean () {
    rm -f "$DLFILE"
}
_ext_clean_install () {
    rm -rf "$CV_INSTDIR"
}
_ext_test () {
    "./bin/$BIN_NAME" --version
}
_ext_help () {
    cat <<EOUSAGE
Usage: $0 CMD

Commands:
$(grep -e "^_ext_.* ()" "$0" | awk '{print $1}' | sed -e 's/_ext_//;s/^/  /g' | tr _ -)
EOUSAGE
    exit 1
}

if [ $# -lt 1 ] ; then
    _ext_help
else
    cmd="$1"; shift
    func="_ext_$(printf "%s\n" "$cmd" | tr - _)"
    if [ -n "${CLIV_DIR:-}" -a -n "${CV_ALIAS:-}" ] ; then
        [ -d "$CLIV_DIR/$CV_ALIAS" ] && cd "$CLIV_DIR/$CV_ALIAS"
    fi
    case "$cmd" in 
        *)                  $func "$@" ;;
    esac
fi
