name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Run tests on a pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v2

      - name: Run test suite
        uses: ./.github/actions/test-with-docker
        env:
          DEBUG: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: |
             *.log
             .clext/*.log
             .clext/tests/*.log
