name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    name: Run tests on a pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v2

      - name: Test pull-request
        uses: ./.github/actions/test-with-docker
        with:
          debug: 1
