name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: alpine-latest
    name: Run tests on a pull request
    steps:
      - name: Checkout git
        uses: actions/checkout@v2

      - name: Test pull-request
        uses: ./.github/actions/test-with-docker
        run: make test
